### ISSUE TITLE
Review authorised market dispute mechanism 

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#142]
Currently the app just supports `SimpleDisputes`. For launch, this mechanism will be removed and replaced with the Authorised mechanism. We need to review the app to made sure that it works end to end with the `Authorised` dispute mechanism.

We should also display the authorised wallet address on market page similarly to how we do with the Oracle and Creator.

**Comment by sea212** [comment]
In case a custom authority is selected (instead of the default Zeitgeist account), it would be very helpful if the app could display the markets (ideally those in the dispute phase) for which the currently used Account in the frontend is the authority. In short, show the users for which markets they are the authority. Helps them make the dispute in-time. I assume this is pretty straight forward with the help of our Subsquid GraphQL endpoint.
I'd consider this low-priority, because a Zeitgeist (proxy) account will be the default and if anybody selects anything different, they should know what they are doing.

**Comment by Robiquet** [comment]
Sounds like a good filter to add to the my markets page
