### ISSUE TITLE
Improve recommended markets 

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/ui#2125]
Instead of just matching markets with similar tags we can use something similar to the search functionality to find closer matches

**Comment by yornaath** [comment]
I think that would be a quite a bit more involved than search since we also have to determine the best input for the "search" for recommended markets, just based on a markets question and description. We cant just fuzzy match on any word since it would be to broad. So it probably would need something like a recomendation engine ala what Algolia have(https://www.algolia.com/doc/guides/algolia-recommend/overview/)

**Comment by Robiquet** [comment]
> I think that would be a quite a bit more involved than search since we also have to determine the best input for the "search" for recommended markets, just based on a markets question and description. We cant just fuzzy match on any word since it would be to broad. So it probably would need something like a recomendation engine ala what Algolia have(https://www.algolia.com/doc/guides/algolia-recommend/overview/)
> 
> Basically when a user search for something the input to filter markets by is already cleaned and formatted in a way that it priortizes what the user wants. But recomending markets based on the data from another market we have to do that process programatically using an algorithm or AI.

I think fuzzy search using market question would be sufficient, we would need to tighten up the relevancy score threshold and fall back to tags if not met. Here is an example:
<img width="574" alt="image" src="https://github.com/zeitgeistpm/ui/assets/4950844/da303cd7-6904-4df0-ac96-fe503927ae28">
