### ISSUE TITLE
It is very hard to create a wallet, get ZTG on it and then use it on zeitgeist.pm 

### ISSUE THREAD

**Issue by Nathanpmyoung** [zeitgeistpm/ui#272]
I know that we know this, but it seems worth surfacing. It is just a huge barrier that there are this many steps.

**Comment by Nathanpmyoung** [comment]
@Robiquet, that looks great, but surely it isn't that simple. Also ZTG isn't on talsiman, right?

**Comment by Robiquet** [comment]
@Nathanpmyoung yeah this is probably the simplest way to get KSM which gets you into the ecosystem. ZTG should be on Talisman but Ramp doesn't list ZTG or any other parachain tokens.

**Comment by Nathanpmyoung** [comment]
Why not?

Yours,

Nathan Young

*M* 07891 020271
*W* nathanpmyoung.com
*T  ***@***.*** <https://twitter.com/nathanpmyoung>

Personal newsletter <https://tinyletter.com/nathanpmyoung>

If I can put you in touch with someone, please ask.

Sent via Superhuman iOS ***@***.***>

**Comment by Robiquet** [comment]
@Nathanpmyoung it's costly to add and maintain these listings so companies need to be convinced that they are going to make a profit from fees.

**Comment by Nathanpmyoung** [comment]
Do we have a sense of how much they need before they will?

Can we lock other currencies? ie have pools of other things?

**Comment by Robiquet** [comment]
@Nathanpmyoung I would say a lot more 
KSM daily volume: $27,498,752
GLMR daily volume (highest volume parachain token): $10,913,100
ZTG daily volume: $125,699.48

I think near term the easiest on ramp would be using some one click XCM magic to transfer KSM to a Dex parachain like Karura, swap for ZTG then transfer to Zeitgeist.

We also plan to support multiple currencies soon so that could help as these currencies might have better on ramps
