### ISSUE TITLE
Reporting scalar markets out of range should be allowed

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#506]
On scalar markets currently it's not allowed to report outcome out of scalar bounds. This should be allowed.

**Comment by lsaether** [comment]
Why should this be allowed? Reporting for the min or the max out of the range is functionally equivalent to reporting as "min or below" or "max or above". I could see an argument for allowing this in order to have consistency on the front-end for displaying the actual result, but functionally it is the same.
