### ISSUE TITLE
Closed markets showing incorrect value for outcomes

### ISSUE THREAD

**Issue by Boibit** [zeitgeistpm/ui#582]
Not entirely sure what is happening here. Below are 3 examples, but you can find more when browsing closed markets on the app. Have not been able to find any common factor between these markets to cause this.

Market ID: 15
Outcome "yes" should have 0 value, not .944
![Image](https://user-images.githubusercontent.com/61936910/212123681-b588152d-b774-4c22-b7e9-13e12875491e.png)

Market ID: 19
Losing outcome "ADA" should have 0 value, not 1. 
Winning outcome "XRP" should have value 1, not .749
![Image](https://user-images.githubusercontent.com/61936910/212125152-6be6571a-180b-4bd4-918b-d1d8704c38c3.png)

Market ID: 1
Losing outcome "Rep" should have 0 value, not 1
Winning outcome "Dem" should have 1 value, no .528
![Image](https://user-images.githubusercontent.com/61936910/212125847-d34e73c5-ac81-48bf-9c29-d15857bc5687.png)

**Comment by saboonikhil** [comment]
Yo @Boibit, these screenshots are very helpful. Thanks a ton!

I find two issues here:
a. Subsquid recalculates price when someone pulls out liquidity post market resolution
_Solution - When market is resolved, set price as constant on subsquid_

b. UI seem to be calculating the prices using amount of tokens present in the pool
_Solution - Since losing assets are not deleted from the pool since `v0.3.6`, UI should either set prices manually (on resolution) or directly fetch from subsquid._

**Comment by Robiquet** [comment]
Fixed in another issue
