### ISSUE TITLE
Onboarding flow / Getting started wizard

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/ui#609]

**Comment by sea212** [comment]
It would be great if we could let the user intuitively select if they want to interact with the testnet or the mainnet. In the former case, some information about token retrieval would be helpful.
This will help the user to test out the functionality and play around with test tokens before utilizing real tokens or even buying real tokens.
This will also aid the development of the protocol, since we have more activity and information available, especially during the phase when new runtime versions are tested.
