### ISSUE TITLE
Calculating price after trade is misleading because of the arbitrage

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/ui#751]
Using  `calcSpotPrice` AMM function to calculate the prediction after trade is showing incorrect result since the arbitrage will change the amounts in the pool after trade happens that is different from the amounts used to calculate the price

**Comment by lsaether** [comment]
@maltekliemann Can you weigh in on this? We're not sure if this is something we should show the user or what the best way to do that would be

**Comment by maltekliemann** [comment]
Just to be safe, we're talking about calculating the impact a user's trade immediately after executing the trade and you're doing this by mimicing what happens with the balances on-chain and then applying the spot price formula, right? I'm assuming that querying the spot price is not an option?

**Comment by lsaether** [comment]
After discussing with the team, we decided to keep the spot price and impact estimation based solely on the trade information and **not include the on-chain arbitrage into the calculation.** The reason why is that the on-chain arbitrage is a system that runs after the initial trade, and doesn't change the impact that the trade has, but modifies it after the fact, and therefore, showing the actual trade impact is more true and straightforward. Also not the least, we would open a can of worms if we wanted to go down this path, which is not worth it since we will remove on-chain arbitrage once the permanent improvements to AMM are made. Therefore, I'm closing this issue as we will not work on it.
