### ISSUE TITLE
Review and remove notifications where no long applicable.

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/ui#926]
The notifications appearing in the top right corner doesn't seem to be needed(at least in most cases) in the new designs.

**Task: review and remove notifications where they aren't needed.**
_Implement new designs for them when and if they are needed as the current design doesnt really fit imho._

For example when buying the modal shows a success step so they can be removed:
![Screenshot 2023-03-24 at 14 10 43](https://user-images.githubusercontent.com/411755/227530504-2d11592c-431c-4551-a97b-732dd3a28483.png)

**Comment by mk26071980** [comment]
We have a new flow. Interaction works on buy
https://www.figma.com/proto/A0OEqjIWy6jL4Rk4kT8ddr/UX%2FUI_Workflow?page-id=3970%3A22391&node-id=4758-12051&viewport=1860%2C-3823%2C0.91&scaling=min-zoom&starting-point-node-id=4758%3A12051

**Comment by Robiquet** [comment]
Could we restyle this:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/4950844/232756815-7b4ea677-ce13-4b5d-8317-4f629f967da2.png">
Instead of adding this?:
<img width="522" alt="image" src="https://user-images.githubusercontent.com/4950844/232757056-c6e00ac0-8cac-4ac6-b6ef-2df1e20f445a.png">
It would make things easy to adjust across the board and I'm not sure the new modal adds much

**Comment by mk26071980** [comment]
There's a restyled notification, if you go to the link. I think the flow similar to the HydraDX one is kinda cool (the one you suggested). But I believe its up to you  whether to implement it or not. Can just use restyled notifications.
